authors:
  - funkypengelf
links:
  - 🎁 Apps: apps/index.md
  # - 👶 Get started: how-to/get-started.md
  - 🚛 Migrate in: how-to/migrate.md
  - 💬 Discord: http://discord.elfhosted.com
search:
  boost: -0.1 
