authors:
  - funkypengelf
links:
  - 🎁 Apps: apps/index.md
  - 💬 Discord: http://discord.elfhosted.com
  - 📺 YouTube: https://youtube.com/@elfhostme
  - 🛒 Store: https://store.elfhosted.com
search:
  boost: -0.1 
