tasks:
  - init: pip install -r requirements.txt
    command: mkdocs serve -f mkdocs-gitpod.yml
    name: serve site
ports:
  - port: 8000
    onOpen: open-browser
    name: Your beautiful preview
vscode:
  extensions:
    - yzhang.markdown-all-in-one
    - davidanson.vscode-markdownlint
    - bpruitt-goddard.mermaid-markdown-syntax-highlighting
